# Generated by Django 4.2.5 on 2024-08-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
