# Generated by Django 5.0.6 on 2024-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_course_id_alter_department_id_alter_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.ManyToManyField(blank=True, to='academic.notes'),
        ),
    ]
