# Generated by Django 5.0.6 on 2024-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_pastpaper1_2_pastpaper2_1_pastpaper2_2_pastpaper3_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes4_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Notes1_1',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='notes',
            new_name='notes1_1',
        ),
        migrations.AddField(
            model_name='course',
            name='notes1_2',
            field=models.ManyToManyField(blank=True, to='academic.notes1_2'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes2_1',
            field=models.ManyToManyField(blank=True, to='academic.notes2_1'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes2_2',
            field=models.ManyToManyField(blank=True, to='academic.notes2_2'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes3_1',
            field=models.ManyToManyField(blank=True, to='academic.notes3_1'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes3_2',
            field=models.ManyToManyField(blank=True, to='academic.notes3_2'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes4_1',
            field=models.ManyToManyField(blank=True, to='academic.notes4_1'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes4_2',
            field=models.ManyToManyField(blank=True, to='academic.notes4_2'),
        ),
    ]
