# Generated by Django 5.0.6 on 2024-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_notes1_2_notes2_1_notes2_2_notes3_1_notes3_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
        migrations.AddField(
            model_name='course',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
