# Generated by Django 5.0.6 on 2024-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_course_modules_course_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper1_1',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
