# Generated by Django 5.0.6 on 2024-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_pastpaper1_1_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper1_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
