# Generated by Django 5.0.6 on 2024-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_pastpaper1_1_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes1_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes1_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes2_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes2_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes3_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes3_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes4_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notes4_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper1_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper2_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper2_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper3_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper3_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper4_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pastpaper4_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
