# Generated by Django 5.1 on 2024-08-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_notes1_1_link_notes1_2_link_notes2_1_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notes1_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes1_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes2_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes2_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes3_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes3_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes4_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes4_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper1_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper1_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper2_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper2_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper3_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper3_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper4_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pastPaper4_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='past_paper',
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes_file', models.FileField(upload_to='notes')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.courseunit')),
            ],
        ),
        migrations.CreateModel(
            name='PastPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='past paper name')),
                ('past_paper_file', models.FileField(upload_to='past papers')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.courseunit')),
            ],
            options={
                'verbose_name_plural': 'past papers',
            },
        ),
        migrations.DeleteModel(
            name='Notes1_1',
        ),
        migrations.DeleteModel(
            name='Notes1_2',
        ),
        migrations.DeleteModel(
            name='Notes2_1',
        ),
        migrations.DeleteModel(
            name='Notes2_2',
        ),
        migrations.DeleteModel(
            name='Notes3_1',
        ),
        migrations.DeleteModel(
            name='Notes3_2',
        ),
        migrations.DeleteModel(
            name='Notes4_1',
        ),
        migrations.DeleteModel(
            name='Notes4_2',
        ),
        migrations.DeleteModel(
            name='PastPaper1_1',
        ),
        migrations.DeleteModel(
            name='PastPaper1_2',
        ),
        migrations.DeleteModel(
            name='PastPaper2_1',
        ),
        migrations.DeleteModel(
            name='PastPaper2_2',
        ),
        migrations.DeleteModel(
            name='PastPaper3_1',
        ),
        migrations.DeleteModel(
            name='PastPaper3_2',
        ),
        migrations.DeleteModel(
            name='PastPaper4_1',
        ),
        migrations.DeleteModel(
            name='PastPaper4_2',
        ),
    ]
