# Generated by Django 5.1 on 2024-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_remove_course_notes1_1_remove_course_notes1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastpapers',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
