# Generated by Django 5.1 on 2024-08-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_notes_year_pastpapers_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastpapers',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
