# Generated by Django 5.0.6 on 2024-07-26 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_images', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('news_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('news_description', models.TextField(blank=True, max_length=200, null=True)),
                ('news_admin', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_date', models.TimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrol',
            fields=[
                ('scrol_images', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('topic', models.CharField(default='Latest News', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slide_image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('slide_topic', models.CharField(default='Latest News', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='my video', max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
