# Generated by Django 5.0.7 on 2024-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_video_date_video_news_admin_video_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_admin',
            field=models.CharField(default='8Tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='news_admin',
            field=models.CharField(default='8Tech', max_length=100),
        ),
    ]
