# Generated by Django 5.0.7 on 2024-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_news_news_admin_alter_news_posted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrol',
            name='scrol_images',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='static/images'),
        ),
    ]
