# Generated by Django 5.0.6 on 2024-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='title',
            field=models.CharField(default='Ads', max_length=100),
        ),
        migrations.AddField(
            model_name='networking',
            name='title',
            field=models.CharField(default='Adds', max_length=100),
        ),
    ]
