# Generated by Django 5.0.6 on 2024-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_items_title_networking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='networking',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
