# Generated by Django 5.0.6 on 2024-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0003_networking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networking',
            name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
