# Generated by Django 5.0.6 on 2024-07-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0005_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='phone',
            field=models.CharField(default='113631232', max_length=9),
        ),
    ]
