# Generated by Django 4.2.5 on 2024-08-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0007_items_sellers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networking',
            name='description',
        ),
    ]
