# Generated by Django 5.0.7 on 2024-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='officials_name',
            field=models.CharField(default='*8Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(default='113631232', max_length=9),
        ),
    ]
