# Generated by Django 5.0.7 on 2024-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_house_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
