# Generated by Django 5.0.7 on 2024-07-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_delete_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.house')),
            ],
        ),
    ]
