# Generated by Django 5.0.7 on 2024-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_housedatails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedatails',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='houseDetails',
            field=models.ManyToManyField(blank=True, to='housing.housedatails'),
        ),
        migrations.AddField(
            model_name='housedatails',
            name='name',
            field=models.CharField(default='House Images', max_length=100),
        ),
        migrations.AlterField(
            model_name='housedatails',
            name='images',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
