# Generated by Django 5.0.7 on 2024-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_remove_housedatails_house_house_housedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
