# Generated by Django 5.0.7 on 2024-07-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_house_available_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='phone',
            field=models.CharField(default='113631232', max_length=9),
        ),
    ]
