# Generated by Django 4.2.5 on 2024-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_house_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='officials_name',
            field=models.CharField(default='8Tech', max_length=100),
        ),
    ]
